# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1df2189e7b8b3ddd41b542716e0a4f8871cb4297326cd7b3624a60b3cf459b823b28e71374e57320230fa773f58795803351479663340a77b6e098027e9fe06

test:
  secret_key_base: 9a37c623aa9fe390a8db45139165050be87c09d8d699c8b6a539a6ea4c841a26119c4bdcfabd5c863037d5f7b9d8fd3aecd15c8d224a493e70496a2898cd3691

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
